#!/bin/zsh

#if [[ "$(pactl get-default-sink)" == "reverse-stereo" ]]; then
#  printf "Audio already reversed\n"
#  return
#fi

sink_number="$(pactl list short sinks | grep "analog-stereo" | awk '{print $1}')"
output="$(pactl load-module module-remap-sink sink_name='reverse-stereo' master=$sink_number channels=2 master_channel_map=front-right,front-left channel_map=front-left,front-right)"

if [[ $? == 0 ]]; then
  pactl set-default-sink "reverse-stereo"
fi
