#!/bin/zsh

local replacements=("piped.kavin.rocks" "piped.projectsegfau.lt" "piped.in.projectsegfau.lt" "piped.video" "yewtu.be")
local args=("$@")
local replaced_args=()

for arg in "${args[@]}"; do
  local replaced_arg="$arg"
  for replacement in "${replacements[@]}"; do
    if [[ "$arg" == *"$replacement"* ]]; then
      replaced_arg="${replaced_arg//$replacement/youtube.com}"
    fi
  done
  replaced_args+=("$replaced_arg")
done
echo "${replaced_args[@]}"
/bin/mpv "${replaced_args[@]}"
