wallpaper {
    monitor = DP-1
    path = /home/matthew/Pictures/Wallpapers/tokyonight/snow-valley.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/matthew/Pictures/Wallpapers/tokyonight/snow-valley.png
    fit_mode = cover
}

splash = false
